/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package chess;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void testsWork() {
        assert (true);
    }
}
